name: Build AIMET Linux Wheel
description: Build AIMET wheel and upload artifact

inputs:
  id:
    description: 'Matrix variant id (e.g. onnx-gpu, torch-gpu)'
    required: true
  ver-torch:
    description: 'VER_TORCH matrix value (empty string if not a torch build)'
    required: false
    default: ''
  ver-onnxruntime:
    description: 'VER_ONNXRUNTIME matrix value (empty string if not an onnx build)'
    required: false
    default: ''
  ver-cuda:
    description: 'VER_CUDA matrix value (empty string for CPU builds)'
    required: false
    default: ''
  pip-index:
    description: 'PIP_INDEX matrix value'
    required: false
    default: ''
  build-targets:
    description: 'SKBUILD_BUILD_TARGETS value'
    required: false
    default: ''
  build-tests:
    description: 'Build C++ tests from ModelOptimizations library (ON/OFF)'
    required: false
    default: 'OFF'

runs:
  using: composite
  steps:
    - name: Make uv accessible to all users
      shell: bash
      run: sudo cp /root/.local/bin/uv ${VIRTUAL_ENV}/bin/uv

    - name: Generate CMAKE_ARGS
      shell: bash
      run: |
        set -x
        ENABLE_TESTS=${{ inputs.build-tests }}
        CMAKE_ARGS="-DENABLE_CUDA=$([ "${{ inputs.ver-cuda }}" = "" ] && echo OFF || echo ON)"
        CMAKE_ARGS="$CMAKE_ARGS -DENABLE_TORCH=$([ "${{ inputs.ver-torch }}" = "" ] && echo OFF || echo ON)"
        CMAKE_ARGS="$CMAKE_ARGS -DENABLE_ONNX=$([ "${{ inputs.ver-onnxruntime }}" = "" ] && echo OFF || echo ON)"
        CMAKE_ARGS="$CMAKE_ARGS -DENABLE_TESTS=$ENABLE_TESTS"
        CMAKE_ARGS="$CMAKE_ARGS -DPIP_INDEX=${{ inputs.pip-index }}"
        echo "AIMET_CMAKE_ARGS=$CMAKE_ARGS" >> $GITHUB_ENV
        echo "AIMET_BUILD_TARGETS=${{ inputs.build-targets }}" >> $GITHUB_ENV

    - name: Exclude Torch libraries from dependencies for manylinux
      if: inputs.ver-torch != '' || inputs.ver-onnxruntime != ''
      shell: bash
      run: |
        . ${VIRTUAL_ENV}/bin/activate
        TORCH_DIR=$(python -c 'import torch; print(f"{torch.utils.cmake_prefix_path}/../../lib")')
        MANYLINUX_EXCLUDE_LIBS="$MANYLINUX_EXCLUDE_LIBS $(find $TORCH_DIR -name '*.so*' | xargs -r patchelf --print-soname | xargs -r printf -- '--exclude %s ')"
        set -x
        echo "MANYLINUX_EXCLUDE_LIBS=$MANYLINUX_EXCLUDE_LIBS" >> $GITHUB_ENV

    - name: Exclude CUDA libraries from dependencies for manylinux
      if: inputs.ver-cuda != ''
      shell: bash
      run: |
        . ${VIRTUAL_ENV}/bin/activate
        CUDART_DIR=$(python -c 'import sysconfig ; from pathlib import Path; print(Path(sysconfig.get_config_var("prefix"), "lib"))')
        MANYLINUX_EXCLUDE_LIBS="$MANYLINUX_EXCLUDE_LIBS $(find $CUDART_DIR -name 'libcu*.so*' -o -name 'libnv*.so*' -o -name 'libnp*.so*' | xargs -r patchelf --print-soname | xargs -r printf -- '--exclude %s ')"
        set -x
        echo "MANYLINUX_EXCLUDE_LIBS=$MANYLINUX_EXCLUDE_LIBS" >> $GITHUB_ENV

    - name: Exclude libpython libraries from dependencies for manylinux
      shell: bash
      run: |
        . ${VIRTUAL_ENV}/bin/activate
        LIBS_DIR=$(python -c 'import sysconfig ; from pathlib import Path; print(Path(sysconfig.get_config_var("prefix"), "lib"))')
        MANYLINUX_EXCLUDE_LIBS="$MANYLINUX_EXCLUDE_LIBS $(find $LIBS_DIR -name 'libpython*.so*' | xargs -r patchelf --print-soname | xargs -r printf -- '--exclude %s ')"
        set -x
        echo "MANYLINUX_EXCLUDE_LIBS=$MANYLINUX_EXCLUDE_LIBS" >> $GITHUB_ENV

    - name: Build AIMET wheel package
      shell: bash
      run: |
        set -x
        . ${VIRTUAL_ENV}/bin/activate
        rm -rf build dist
        export CMAKE_ARGS="$AIMET_CMAKE_ARGS"
        export SKBUILD_BUILD_TARGETS="$AIMET_BUILD_TARGETS"

        python -m build --wheel --no-isolation .

        # Run auditwheel only for aimet_onnx. (aimet_torch doesn't contain any shared library)
        if [ -n "${{ inputs.ver-onnxruntime }}" ]; then
          auditwheel repair --plat manylinux_2_34_x86_64 $MANYLINUX_EXCLUDE_LIBS dist/aimet*.whl
        else
          mkdir -p wheelhouse
          cp dist/aimet*.whl wheelhouse/
        fi

        if [ "${{ inputs.id }}" == "onnx-torch-cpu" ] ; then
          uv pip install -t wheelhouse --no-deps wheelhouse/aimet*.whl
        fi

    - name: Re-tag aimet-torch wheel files
      if: inputs.ver-torch != ''
      shell: bash
      run: |
        set -x
        . ${VIRTUAL_ENV}/bin/activate
        ${VIRTUAL_ENV}/bin/uv pip install wheel
        wheel tags --remove --python-tag=py310 --abi-tag=none --platform-tag=any wheelhouse/aimet*.whl
        ls -al wheelhouse/

    - name: Upload AIMET wheel file
      if: inputs.id != 'onnx-torch-cpu'
      uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.id }}-wheel"
        path: wheelhouse/aimet*.whl
        if-no-files-found: error
        retention-days: 30

    - name: Upload compiled C++ unit tests
      if: (inputs.id == 'onnx-cpu' || inputs.id == 'onnx-gpu') && inputs.build-tests == 'ON'
      uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.id }}-tests"
        path: build/**/MoDl*Test
        if-no-files-found: error
        retention-days: 1

    - name: Upload AIMET documentation
      if: inputs.id == 'onnx-torch-cpu'
      uses: actions/upload-artifact@v3
      with:
        name: Docs
        path: wheelhouse/Docs/
        if-no-files-found: error
        retention-days: 30
