# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

# pylint: disable=protected-access
import torch


def _is_grid_preserving_op(node: torch.fx.Node) -> bool:
    if not isinstance(node.target, torch._ops.OpOverload):
        return False

    name, *_ = node.target.name().split(".")
    return name in (
        "aten::contiguous",
        "aten::copy",
        "aten::copy_",
        "aten::detach",
        "aten::diag",
        "aten::diag_embed",
        "aten::diagonal",
        "aten::diagonal_backward",
        "aten::diagonal_copy",
        "aten::dropout",
        "aten::dropout_",
        "aten::embedding",
        "aten::expand",
        "aten::flatten",
        "aten::gather",
        "aten::item",
        "aten::kthvalue",
        "aten::masked_select",
        "aten::max_pool1d",
        "aten::max_pool2d",
        "aten::max_pool2d_with_indices",
        "aten::max_pool3d",
        "aten::max_pool3d_with_indices",
        "aten::max",
        "aten::min",
        "aten::narrow",
        "aten::narrow_copy",
        "aten::native_dropout",
        "aten::nonzero",
        "aten::pad",
        "aten::permute",
        "aten::permute_copy",
        "aten::reflection_pad1d",
        "aten::reflection_pad2d",
        "aten::reflection_pad3d",
        "aten::relu",
        "aten::relu_",
        "aten::repeat",
        "aten::repeat_interleave",
        "aten::replication_pad1d",
        "aten::replication_pad2d",
        "aten::replication_pad3d",
        "aten::reshape",
        "aten::rot90",
        "aten::select",
        "aten::slice",
        "aten::squeeze",
        "aten::t",
        "aten::t_",
        "aten::t_copy",
        "aten::take",
        "aten::tile",
        "aten::topk",
        "aten::transpose",
        "aten::transpose_",
        "aten::transpose_copy",
        "aten::unfold",
        "aten::unfold_backward",
        "aten::unfold_copy",
        "aten::unsqueeze",
        "aten::unsqueeze_",
        "aten::unsqueeze_copy",
        "aten::view",
        "aten::view_copy",
        "aten::zeros_like",
    )
