model_name: convnext_tiny
qnn_options: null

tests:
  - name: quantsim_int8_int16
    feature: quantsim
    quant_scheme: min_max
    param_type: int8
    activation_type: int16
    config_file: htp_v79
    apply_experimental_static_aten_calibration: true
