model_name: ddrnet23_slim

tests:
  - name: quantsim_int8_v79
    feature: quantsim
    quant_scheme: min_max
    param_type: int8
    activation_type: int8
    config_file: htp_v79
    max_accuracy_drop_onnx: 1.5
