model_name: hrnet_pose
apply_prepare_model: true
qnn_options: null

tests:
  - name: quantsim_int8_v79
    feature: quantsim
    quant_scheme: min_max
    param_type: int8
    activation_type: int8
    config_file: htp_v79
    apply_experimental_static_aten_calibration: true
    max_accuracy_drop_onnx: 2.5
    max_accuracy_drop_torch: 2.1
