model_name: mobilenet_v3_large
tests:

  - name: amp_int8_fp16_fast
    feature: mixed_precision
    mode: manual
    precision_config:
      Sigmoid: {activation: fp16, param: fp16}
      Hardsigmoid: {activation: fp16, param: fp16}
      ReLU: {activation: fp16, param: int8}
    candidates: int8_fp16
    enable_sqnr_pruning: true
    phase1_samples: 1000
    phase2_samples: 1000
    allowed_accuracy_drop: 0.02
    config_file: htp_v79
    quant_scheme: min_max
    param_type: int8
    activation_type: int8
    calib_samples: 1000
    eval_samples: 1000
    max_accuracy_drop_onnx: 2.0
    max_accuracy_drop_torch: 6.5

  - name: quantsim_int8_v79
    feature: quantsim
    quant_scheme: min_max
    param_type: int8
    activation_type: int8
    config_file: htp_v79
    max_accuracy_drop_onnx: 5.1
    max_accuracy_drop_torch: 7.1
    apply_experimental_static_aten_calibration: true

  - name: quantsim_int8_int16
    feature: quantsim
    quant_scheme: min_max
    param_type: int8
    activation_type: int16
    config_file: htp_v81
    max_accuracy_drop_onnx: 1.5
    max_accuracy_drop_torch: 4.0
    apply_experimental_static_aten_calibration: true
