model_name: regnet
qnn_options: null

tests:
  - name: quantsim_int8
    feature: quantsim
    quant_scheme: min_max
    param_type: int8
    activation_type: int8
    config_file: htp_v79

  - name: adaround_500
    feature: adaround
    quant_scheme: min_max
    param_type: int8
    activation_type: int8
    config_file: htp_v79
    adaround_iters: 500
    max_accuracy_drop_onnx: 1.3
