model_name: segformer_base
qnn_options: null
apply_prepare_model: True

tests:
  - name: quantsim_int8
    feature: quantsim
    quant_scheme: min_max
    param_type: int8
    activation_type: int8
    config_file: htp_v79
    max_accuracy_drop_torch: 1.2
    apply_experimental_static_aten_calibration: true

  - name: quantsim_int8_int16
    feature: quantsim
    quant_scheme: min_max
    param_type: int8
    activation_type: int16
    config_file: htp_v81
    apply_experimental_static_aten_calibration: true
