model_name: yolov5
apply_prepare_model: False

tests:
  - name: quantsim_int8_int16
    feature: quantsim
    quant_scheme: min_max
    param_type: int8
    activation_type: int16
    config_file: htp_v79
    # TODO: Uncomment this with qai-hub-models v0.55
    # apply_experimental_static_aten_calibration: true
