model:
  name: Llama_32
  sequence_length: 2048
  context_length: 4096
recipe:
  name: RemoveQuantization
metrics:
  - name: TinyMMLU
  - name: PPL
---
model:
  name: Llama_32
  sequence_length: 2048
  context_length: 4096
recipe:
  name: LPBQ
  dataset:
    name: Wikitext
    split: train
metrics:
  - name: TinyMMLU
  - name: PPL
---
model:
  name: Llama_32
  sequence_length: 2048
  context_length: 4096
recipe:
  name: PCQ
  dataset:
    name: Wikitext
    split: train
metrics:
  - name: TinyMMLU
  - name: PPL
---
model:
  name: Llama_32
  sequence_length: 2048
  context_length: 4096
recipe:
  name: SeqMSE
  dataset:
    name: Wikitext
    split: train
metrics:
  - name: TinyMMLU
  - name: PPL
