name: Setup UV environment with AIMET

description: Creates UV virtual environment and installs AIMET wheel

inputs:
  ENV_NAME:
    description: "UV environment name"
    required: true
  VER_PYTHON:
    description: "Python version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      id: windows_init
      run: |
        irm https://astral.sh/uv/install.ps1 | iex

    - name: Create uv environment (Windows)
      shell: powershell
      if: runner.os == 'Windows'
      run: |
        uv venv --python "${{ inputs.VER_PYTHON }}" "${{ inputs.ENV_NAME }}"
        .\"${{ inputs.ENV_NAME }}"\Scripts\Activate.ps1

