model_name: mobilenet_v2
feature: quantsim
framework: onnx
quant_scheme: tf_enhanced
tolerance: 0.5
baseline_accuracy: 72.8
device: Samsung Galaxy S24 (Family)
qnn_options: "--target_runtime qnn_lib_aarch64_android"
qnn_eval_samples: 50
