model_name: mobile_vit
feature: quantsim
framework: onnx
quant_scheme: tf_enhanced
param_type: int8
activation_type: int8
config_file: htp_v79
device: Samsung Galaxy S24 (Family)
qnn_options: "--target_runtime qnn_lib_aarch64_android"
qnn_eval_samples: 50