model_name: resnet50
feature: quantsim
framework: onnx
quant_scheme: tf_enhanced
param_type: int8
activation_type: int8
config_file: htp_v79
quant_eval_samples: 50
device: Samsung Galaxy S24 (Family)
qnn_options: "--target_runtime qnn_dlc"
qnn_eval_samples: 50