# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

"""Grade free-form LLM responses with a grader LLM on a 0-10 rubric.

The rubric and summary templates below are load-bearing: editing a single word
moves every score, so a change here needs a ``GRACE_VERSION`` bump.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field

import torch
from tqdm import tqdm
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    LogitsProcessor,
    PreTrainedModel,
    PreTrainedTokenizerBase,
)

MAX_POINTS: int = 10

# Two sentences plus the rating is ~60 tokens; the rest is slack for a grader
# that pads a little before committing.
DEFAULT_MAX_RATIONALE_TOKENS: int = 320
# A rationale past this length is the grader deliberating, not reporting.
MAX_RATIONALE_CHARS: int = 400

# Recurring failure modes reported by the closing summary pass.
MAX_SUMMARY_ITEMS: int = 5
# Five short phrases, with slack for a model that pads before listing.
DEFAULT_MAX_SUMMARY_TOKENS: int = 384
# Items have to fit a markdown table cell in the CI summary, so they are phrases
# rather than sentences.
MAX_SUMMARY_ITEM_CHARS: int = 90

RATIONALE_PREFIX = "Rationale:"
# Prefixed to the rationale of an item the grader never rated. Scored 0, so it
# has to be attributable to the grader and not read as a model defect.
GRADER_FAILURE_NOTE = "GRADER FAILURE: no rating produced, scored 0."
# Appended to a rationale that ran out of tokens before rating, to make the rating
# the only thing left to generate. See ResponseGrader._force_rating.
RATING_FORCE_SUFFIX = "\n\nRating: [["
# Enough for "10]]" plus a stray space.
FORCED_RATING_TOKENS: int = 4
# Generation stops if the grader rolls on into a fabricated next example.
STOP_STRINGS: tuple[str, ...] = ("--- Prompt ---", "--- Response to grade ---")
# Nothing useful follows the rating, so stop as soon as it closes. Kept out of
# STOP_STRINGS because those are *stripped*, and the regex needs the brackets.
RATING_STOP = "]]"

_SUMMARY_BULLET_RE = re.compile(r"^\s*(?:\d{1,2}\s*[.)]|[-*•])\s+")
_RATING_RE = re.compile(r"\[\[\s*(\d{1,2})\s*\]\]")
# Fallback for a grader that drops the brackets it was asked for.
_BARE_RATING_RE = re.compile(r"\bRating\b\s*:?\s*(\d{1,2})", re.IGNORECASE)
_RATING_MARKER_RE = re.compile(r"\bRating\b\s*:?|\[\[", re.IGNORECASE)
# The forced pass emits the number first, so "]]" never has to arrive.
_FORCED_TAIL_RE = re.compile(r"\s*(\d{1,2})")
_WHITESPACE_RE = re.compile(r"\s+")

DEFAULT_PROMPT_TEMPLATE = """You are grading text generated by a language model running on quantized hardware. Quantization damages a model in characteristic ways — corrupted tokens, repeated words, foreign script leaking into English — and your job is to say how damaged this response is. Ordinary weaknesses count too, but far less than corruption.

Rate the response from 0 to 10. Any integer is allowed. The bands:

0 — Empty, or so garbled it does not read as language.

1-3 — A decoding failure. Any one of: junk or nonsense tokens ("pep-e-e-e-e", "10-15-15-15-15"); mojibake or broken encoding ("Saut?", "pur ed" for "puréed", "68-72?F"); non-English script dropped into an English sentence; a degenerate loop repeating until the token limit; the same sentence or paragraph restated almost verbatim several times; text truncated mid-sentence or starting mid-sentence. These are the worst thing a response can have: one clear instance belongs in this band even if everything else about the response is excellent.

4-6 — Fluent, well-formed English with no decoding failure, but a real flaw. Any one of: a duplicated word or short phrase that a reader reads straight past ("trained on large datasets, datasets, and evaluated on held-out data"); a dangling "**" or a header with no closing marker; a misspelling ("constanty", "Frittatta"); code with a syntax error or a call to a function that was never defined; a blatant factual or arithmetic error (Newton born in 1492, a sum that is wrong, a unit conversion off by 1000x). One such flaw is about 5.

A duplicated word is the mildest flaw in this band — the sentence still reads correctly and the meaning survives — so rate it 5 or 6. It only drops into 1-3 if the duplication keeps happening, at which point it is a loop rather than a stumble.

7-9 — Fluent, accurate English with no decoding failure and no blatant error. Come down into this band for reasoning that does not hold up: an unsupported leap, a conclusion that does not follow from the argument, an analogy that breaks down, a self-contradiction, or padding that avoids answering. Clearly shaky logic is about 7; a small nitpick is 9.

10 — No issues. Coherent, fluent, accurate, and it answers what was asked.

Do not be nitpicky. These are NOT flaws: style, tone, verbosity, redundant section headers, emoji, formatting taste, hedging, or a response being shorter than you would have written. A translation request answered in the target language is correct, not foreign script. Punctuation inside or outside quotes and bold markers is not a defect.

Write at most two short sentences saying what is wrong, or that nothing is. Then give the rating on its own line, in exactly this format:

Rating: [[N]]

Commit to one rating even if you are torn. Do not restart your analysis or argue with yourself.

Here are worked examples.

--- Prompt ---
Describe how objects fall.
--- Response to grade ---
The the is and the to to to to a a a a a a a the the the the the the to to to to
--- End of response ---
Rationale: Degenerate token repetition throughout; this does not read as language at all.
Rating: [[0]]

--- Prompt ---
What is gravity?
--- Response to grade ---
Gravity is a fundamental force that attracts any two objects with mass or energy. The acceleration of自由下落的物体 on Earth is approximately 9.81 m/s^2.
--- End of response ---
Rationale: Chinese text is dropped into the middle of an English sentence. The rest of the answer is correct and fluent.
Rating: [[2]]

--- Prompt ---
Give me a recipe for herb butter.
--- Response to grade ---
flowers, 1/4 teaspoon of thyme buds, 1/4 teaspoon of thyme leaves, 1/4 teaspoon of thyme flowers, 1/4 teaspoon of thyme buds, 1/4 teaspoon of thyme leaves, 1/4 teaspoon of thyme flowers, 1/4 teaspoon of thyme buds, 1/4 teaspoon of
--- End of response ---
Rationale: Starts mid-sentence and then loops on "1/4 teaspoon of thyme" until the token limit.
Rating: [[1]]

--- Prompt ---
Suggest a dish using eggs and onions.
--- Response to grade ---
Try a French frittata, which is a type of omelet. Saut? the onions first, then pour in the beaten eggs and cook until set.
--- End of response ---
Rationale: "Saut?" is a broken encoding of "Sauté". The cooking advice itself is sound.
Rating: [[2]]

--- Prompt ---
How does a neural network learn?
--- Response to grade ---
A neural network learns by adjusting its weights to reduce the error between its predictions and the correct answers. It is trained on large datasets, datasets, and then evaluated on data it has never seen.
--- End of response ---
Rationale: Fluent and accurate, with one duplicated word ("datasets, datasets") that does not obscure the meaning.
Rating: [[6]]

--- Prompt ---
How do I change a tire?
--- Response to grade ---
Loosen the lug nuts before you jack up the car. Then raise the vehicle, remove the nuts, and swap the wheel.**

Tighten in a star pattern.
--- End of response ---
Rationale: Fluent and correct, but there is a dangling bold marker after "swap the wheel."
Rating: [[5]]

--- Prompt ---
If 5 machines make 5 widgets in 5 minutes, how long for 100 machines to make 100 widgets?
--- Response to grade ---
Each machine makes 1 widget in 5 minutes. So 100 widgets / (1 widget per 5 minutes) = **200 minutes**. At the original rate, it will take 200 minutes for all 5 machines to finish.
--- End of response ---
Rationale: The arithmetic is blatantly wrong — the answer is 5 minutes — and the last sentence contradicts the premise by referring to 5 machines.
Rating: [[4]]

--- Prompt ---
Should I bike or drive for a 2 km commute?
--- Response to grade ---
You should bike. Cars are always slower than bicycles in city traffic, and 2 km is too short a distance for a car to be worth using at all.
--- End of response ---
Rationale: Clean, fluent English, but "always slower" is an unsupported absolute and the conclusion rests on it.
Rating: [[7]]

--- Prompt ---
What is gravity?
--- Response to grade ---
Gravity is the attractive force that exists between any two objects with mass. Its strength grows with the masses involved and falls off with the square of the distance between them, as described by Newton's law of universal gravitation.
--- End of response ---
Rationale: Accurate, fluent, and directly answers the question.
Rating: [[10]]

Now grade the following response. Remember: decoding failures sit at the bottom of the scale, a single duplicated word is a mid-band flaw rather than a decoding failure, and you are not looking for nitpicks.

--- Prompt ---
{prompt}
--- Response to grade ---
{response}
--- End of response ---
Rationale:"""

SUMMARY_PROMPT_TEMPLATE = """Below are {num_notes} grader notes on text generated by one language model running on quantized hardware. Each line is a grader's verdict on one response. The questions are not shown and do not matter here.

List the recurring defects in this model's output, at most {max_items} of them, worst first.

Each item is one short phrase naming the defect, then how widespread it is in brackets. At most 8 words. Not a sentence. Exactly this shape:

1. Blatant factual errors (most responses)
2. Duplicated words mid-sentence (several)
3. Degenerate loops until the token limit (a couple)

- Defects only. Never list a strength, and never say the responses are fine alongside items saying they are not.
- A note starting "GRADER FAILURE" is a fault in the grading run, not in the model. If any appear, list them first as "GRADER FAILURE: no rating produced (<frequency>)" and do not fold them in with the model's defects.
- One item per defect: merge the duplicates. There is one note per response, so count the notes mentioning a defect to pick its frequency — most, many, several, a couple, one.
- Only what the notes report. Do not invent defects, quote responses, or cite note numbers.
- Fewer items is better than padding: stop when the recurring defects are covered. If almost every note reports nothing wrong, the whole list is "No recurring defects".

Output the numbered list and nothing else — no preamble, no closing remarks, no sub-bullets.

--- Grader notes ---
{notes}
--- End of grader notes ---
"""


@dataclass
class GradeResult:
    """Per-item grading result.

    The grader emits one blob of text per item. ``grader_output`` is that whole
    blob: the justification *and* the trailing ``Rating: [[N]]`` line.
    ``rationale`` is the one-line justification cut out of it — same words,
    rating line removed, whitespace collapsed, truncated to
    :data:`MAX_RATIONALE_CHARS`. Reports show ``rationale``; ``grader_output``
    is kept for debugging what the grader actually wrote. Neither holds the
    graded model's response.

    ``points`` is the 0-10 rating and is always meaningful. ``skipped`` is True
    when the model was bypassed (empty response, scored 0 outright).
    ``parsed`` is False when no rating could be read even after the forced pass;
    the item still scores 0 and still counts. ``forced`` marks a rating
    recovered by the second pass rather than written outright.
    """

    points: int
    skipped: bool
    rationale: str = ""
    grader_output: str = ""
    parsed: bool = True
    forced: bool = False


@dataclass
class GradeSummary:
    """Aggregated grading results.

    ``max_points`` covers *every* item, including ones the grader failed on —
    those score 0. See :func:`summarize`. ``summary_items`` are the recurring
    failure modes distilled from the rationales, and are empty when the summary
    pass was not run.
    """

    results: list[GradeResult]
    total_points: int
    max_points: int
    summary_items: list[str] = field(default_factory=list)

    @property
    def score_pct(self) -> float:
        if self.max_points == 0:
            return 0.0
        return 100.0 * self.total_points / self.max_points

    @property
    def num_unparsed(self) -> int:
        """Items scored 0 because the grader produced no readable rating."""
        return sum(1 for result in self.results if not result.parsed)

    @property
    def num_forced(self) -> int:
        """Items whose rating came from the forced second pass."""
        return sum(1 for result in self.results if result.forced)


def resolve_device(device: str | None = None, allow_cpu: bool = False) -> str:
    """Resolve the grader device, refusing a silent CPU fallback.

    A GPU host whose torch build doesn't match the CUDA driver reports no CUDA,
    so the grader quietly runs a 35B model on CPU: ~13 minutes per file instead
    of seconds, exiting 0 the whole time. CI then reports success while having
    burned a GPU reservation on a CPU run.

    Parameters
    ----------
    device
        Explicit device, or None to auto-detect.
    allow_cpu
        Permit CPU. Only set this when CPU is genuinely intended.

    Returns
    -------
    str
        The resolved device string.

    Raises
    ------
    RuntimeError
        If CPU was resolved by fallback rather than requested.
    """
    resolved = device or ("cuda" if torch.cuda.is_available() else "cpu")
    if resolved == "cpu" and not allow_cpu:
        raise RuntimeError(
            f"Refusing to grade on CPU (torch {torch.__version__}, "
            f"torch.version.cuda={torch.version.cuda}, "
            f"torch.cuda.is_available()={torch.cuda.is_available()}).\n"
            "On a GPU host this usually means the installed torch wheel's CUDA "
            "version doesn't match the driver, so torch silently disables CUDA. "
            "Pass allow_cpu=True to grade on CPU anyway."
        )
    return resolved


class _ForceFirstToken(LogitsProcessor):
    """Restrict only the first generated token to ``allowed``.

    Used to guarantee the forced rating pass emits a digit instead of, say, a
    newline or a bracket, which would leave nothing to parse.
    """

    def __init__(self, allowed: list[int], prompt_len: int) -> None:
        self.allowed = allowed
        self.prompt_len = prompt_len

    def __call__(
        self, input_ids: torch.LongTensor, scores: torch.FloatTensor
    ) -> torch.FloatTensor:
        if input_ids.shape[1] > self.prompt_len:
            return scores
        masked = torch.full_like(scores, float("-inf"))
        masked[:, self.allowed] = scores[:, self.allowed]
        return masked  # type: ignore[return-value]


def _rating_token_ids(tokenizer: PreTrainedTokenizerBase) -> list[int]:
    """Token ids that can *start* a valid 0-10 rating.

    "10" tokenizes as "1"+"0" in the Qwen graders, so only the first token is
    constrained and a forced 10 arrives across two. The width check catches a
    grader swap whose tokenizer splits a rating wider than the forced pass
    generates, which would leave the number truncated and misparsed.
    """
    first_ids = set()
    widest = 0
    for value in range(MAX_POINTS + 1):
        encoded = tokenizer.encode(str(value), add_special_tokens=False)
        if not encoded:
            raise ValueError(
                f"Tokenizer {tokenizer.name_or_path} encodes rating {value} as no "
                "tokens; the forced rating pass cannot be constrained."
            )
        first_ids.add(int(encoded[0]))
        widest = max(widest, len(encoded))
    if widest > FORCED_RATING_TOKENS:
        raise ValueError(
            f"Tokenizer {tokenizer.name_or_path} needs {widest} tokens for the "
            f"widest 0-{MAX_POINTS} rating, but the forced pass generates only "
            f"{FORCED_RATING_TOKENS}; raise FORCED_RATING_TOKENS to at least "
            f"{widest}."
        )
    return sorted(first_ids)


class ResponseGrader:
    """Loads a grader model once and grades batches of (question, response) items."""

    def __init__(
        self,
        model_id: str,
        device: str | None = None,
        dtype: torch.dtype = torch.bfloat16,
        prompt_template: str = DEFAULT_PROMPT_TEMPLATE,
        allow_cpu: bool = False,
        max_rationale_tokens: int = DEFAULT_MAX_RATIONALE_TOKENS,
        max_summary_tokens: int = DEFAULT_MAX_SUMMARY_TOKENS,
        device_map: str | None = None,
    ) -> None:
        if "{response}" not in prompt_template:
            raise ValueError(
                "Prompt template must contain the '{response}' placeholder."
            )
        device = resolve_device(device, allow_cpu=allow_cpu)
        self.model_id = model_id
        self.device = device
        self.dtype = dtype
        self.prompt_template = prompt_template
        self.max_new_tokens = max_rationale_tokens
        self.max_summary_tokens = max_summary_tokens
        self.tokenizer, self.model = _load_model(
            model_id, device, dtype, device_map=device_map
        )
        self.rating_token_ids = _rating_token_ids(self.tokenizer)

    @torch.no_grad()
    def grade_one(self, prompt: str, output: str) -> GradeResult:
        """Grade one prompt/output pair.

        ``prompt`` is passed through to the grading template raw — chat-template
        tokens or a system block are left in. Stripping those is template-
        specific (Qwen vs Llama 3 vs Llama 2 vs ...) and out of scope here.
        """
        if not output.strip():
            # Hard override: empty/whitespace-only outputs always score 0. Small
            # grader LLMs have been unreliable at penalizing these on their own,
            # even with explicit rubric guidance.
            return GradeResult(points=0, skipped=True, rationale="Empty response.")

        rubric = self.prompt_template.replace("{prompt}", prompt).replace(
            "{response}", output
        )
        prefix = self._apply_chat_template(rubric)
        grader_output = self._generate(prefix)
        rating = parse_rating(grader_output)
        forced = False
        if rating is None:
            # The grader talked past its token budget without rating. Rather than
            # drop the item, hand it back its own words plus "Rating: [[".
            rating = self._force_rating(prefix, grader_output)
            forced = rating is not None
        parsed = rating is not None
        rationale = parse_rationale(grader_output)
        if not parsed:
            # Scored 0, so the rationale has to say the grader failed rather than
            # the response did — otherwise the summary pass reports a phantom
            # model defect and nobody looks at the grader.
            rationale = f"{GRADER_FAILURE_NOTE} {rationale}".strip()
        return GradeResult(
            points=0 if rating is None else rating,
            skipped=False,
            rationale=rationale,
            grader_output=grader_output,
            parsed=parsed,
            forced=forced,
        )

    @torch.no_grad()
    def _force_rating(self, prefix: str, grader_output: str) -> int | None:
        """Re-run generation with the rating line already begun.

        The continuation resumes from whatever the grader had written, so the
        rating reflects its own unfinished reasoning rather than a fresh read.
        """
        forced_prefix = f"{prefix}{grader_output}{RATING_FORCE_SUFFIX}"
        inputs = self.tokenizer(
            forced_prefix, return_tensors="pt", add_special_tokens=False
        ).to(self.model.device)  # type: ignore[attr-defined, unused-ignore]
        prompt_len = int(inputs["input_ids"].shape[1])
        generated = self.model.generate(  # type: ignore[attr-defined, operator, unused-ignore]
            **inputs,
            max_new_tokens=FORCED_RATING_TOKENS,
            do_sample=False,
            stop_strings=[RATING_STOP],
            tokenizer=self.tokenizer,
            pad_token_id=self.tokenizer.pad_token_id or self.tokenizer.eos_token_id,
            logits_processor=[
                _ForceFirstToken(self.rating_token_ids, prompt_len),
            ],
        )
        tail: str = self.tokenizer.decode(  # type: ignore[assignment, unused-ignore]
            generated[0, prompt_len:], skip_special_tokens=True
        )
        return parse_forced_rating(tail)

    def _apply_chat_template(self, rubric: str) -> str:
        """Wrap the filled rubric as a single user turn.

        Falls back to the bare rubric for tokenizers without a chat template.
        Reasoning is turned off: the rationale budget has no room for a thinking
        block, and a grader that spends it deliberating never reaches a rating.
        The kwarg is only passed when the template mentions it, since templates
        that don't accept it raise.
        """
        template = self.tokenizer.chat_template
        if not template:
            return f"{rubric}\n{RATIONALE_PREFIX}"
        if "enable_thinking" in template:
            return self.tokenizer.apply_chat_template(  # type: ignore[return-value, unused-ignore]
                [{"role": "user", "content": rubric}],
                tokenize=False,
                add_generation_prompt=True,
                enable_thinking=False,
            )
        return self.tokenizer.apply_chat_template(  # type: ignore[return-value, unused-ignore]
            [{"role": "user", "content": rubric}],
            tokenize=False,
            add_generation_prompt=True,
        )

    def _generate(
        self,
        prefix: str,
        max_new_tokens: int | None = None,
        stop_strings: Sequence[str] | None = (*STOP_STRINGS, RATING_STOP),
    ) -> str:
        """Generate the rationale and rating (and reasoning block, if enabled)."""
        inputs = self.tokenizer(
            prefix, return_tensors="pt", add_special_tokens=False
        ).to(self.model.device)  # type: ignore[attr-defined, unused-ignore]
        generated = self.model.generate(  # type: ignore[attr-defined, operator, unused-ignore]
            **inputs,
            max_new_tokens=max_new_tokens or self.max_new_tokens,
            do_sample=False,
            # An empty list would build a StopStringCriteria over nothing and raise.
            stop_strings=list(stop_strings) if stop_strings else None,
            tokenizer=self.tokenizer,
            pad_token_id=self.tokenizer.pad_token_id or self.tokenizer.eos_token_id,
        )
        new_tokens = generated[0, inputs["input_ids"].shape[1] :]
        text: str = self.tokenizer.decode(new_tokens, skip_special_tokens=True)  # type: ignore[assignment, unused-ignore]
        for stop in STOP_STRINGS:
            text = text.split(stop, 1)[0]
        return text.strip()

    @torch.no_grad()
    def summarize_rationales(
        self,
        rationales: Iterable[str],
        max_items: int = MAX_SUMMARY_ITEMS,
    ) -> list[str]:
        """Distil the per-item rationales into at most ``max_items`` failure modes.

        Only the rationales are shown to the model — no questions, no responses,
        no scores. Each is already capped at
        :data:`MAX_RATIONALE_CHARS`, so a full 100-item run is a few thousand
        tokens of input.

        Parameters
        ----------
        rationales
            Per-item rationales. Blank ones are dropped.
        max_items
            Upper bound on the number of items returned.

        Returns
        -------
        list[str]
            The summary items, or an empty list if there was nothing to
            summarize or the model produced nothing parseable.
        """
        notes = [text.strip() for text in rationales if text.strip()]
        if not notes:
            return []
        prompt = (
            SUMMARY_PROMPT_TEMPLATE.replace("{num_notes}", str(len(notes)))
            .replace("{max_items}", str(max_items))
            .replace("{notes}", "\n".join(f"- {note}" for note in notes))
        )
        text = self._generate(
            self._apply_chat_template(prompt),
            max_new_tokens=self.max_summary_tokens,
            stop_strings=None,
        )
        return parse_summary_items(text, max_items=max_items)

    def grade(
        self, items: Iterable[dict[str, str]], summary: bool = True
    ) -> GradeSummary:
        """Grade a sequence of items, each with at least ``prompt`` and ``output`` keys.

        Extra keys (e.g. ``idx``) are ignored. Unless ``summary`` is False, a
        closing pass condenses the rationales into recurring failure modes.
        """
        results = [
            self.grade_one(item["prompt"], item["output"])
            for item in tqdm(list(items), desc="Grading responses")
        ]
        graded = summarize(results)
        if summary:
            graded.summary_items = self.summarize_rationales(
                result.rationale for result in results
            )
        return graded


def summarize(results: list[GradeResult]) -> GradeSummary:
    """Total the points over every item.

    An item the grader failed to rate scores 0 and stays in the denominator. A
    grader failure is still a failure to measure, and dropping it would quietly
    inflate the score by whatever fraction of the set went unread.
    """
    return GradeSummary(
        results=results,
        total_points=sum(result.points for result in results),
        max_points=MAX_POINTS * len(results),
    )


def parse_rating(grader_output: str) -> int | None:
    """Read the 0-10 rating out of the grader's output.

    Prefers the requested ``[[N]]`` form and falls back to a bare ``Rating: N``.
    The *last* match wins, since the rating is asked for last and a rationale
    can quote a number of its own. Out-of-range values are clamped rather than
    discarded: a grader that writes ``[[12]]`` means the top of the scale.
    Returns None if there is no rating to read at all.
    """
    matches = _RATING_RE.findall(grader_output) or _BARE_RATING_RE.findall(
        grader_output
    )
    if not matches:
        return None
    return min(MAX_POINTS, max(0, int(matches[-1])))


def parse_forced_rating(tail: str) -> int | None:
    """Read the rating out of a forced continuation of ``Rating: [[``.

    Only the leading number is considered, and the closing ``]]`` is not
    required: the continuation is constrained to start with a digit, so anything
    after that number is noise.
    """
    match = _FORCED_TAIL_RE.match(tail)
    if not match:
        return None
    return min(MAX_POINTS, max(0, int(match.group(1))))


def parse_rationale(grader_output: str, max_chars: int = MAX_RATIONALE_CHARS) -> str:
    """Extract the justification, as a single line, without the rating.

    Everything from the rating marker on is dropped; if the grader led with the
    rating instead, what follows it is used. Whitespace is collapsed so the
    rationale stays one line in reports, and an over-long one is truncated —
    past a few hundred characters the grader is arguing with itself, and the
    tail adds nothing.
    """
    text = grader_output.strip().removeprefix(RATIONALE_PREFIX).strip()
    marker = _RATING_MARKER_RE.search(text)
    if marker:
        before = text[: marker.start()].strip()
        text = before if before else _strip_leading_rating(text[marker.start() :])
    text = _WHITESPACE_RE.sub(" ", text).strip()
    if len(text) > max_chars:
        text = text[:max_chars].rstrip() + "…"
    return text


def parse_summary_items(
    text: str,
    max_items: int = MAX_SUMMARY_ITEMS,
    max_chars: int = MAX_SUMMARY_ITEM_CHARS,
) -> list[str]:
    """Read the closing summary's numbered list into individual items.

    Bullet and number markers are stripped. Lines carrying no marker are kept
    only when the model listed nothing at all, so that a preamble ("Here are the
    problems:") does not become an item while a plain-prose answer still
    survives.
    """
    lines = [line.strip() for line in text.strip().splitlines()]
    marked = [
        _SUMMARY_BULLET_RE.sub("", line)
        for line in lines
        if _SUMMARY_BULLET_RE.match(line)
    ]
    candidates = marked or [line for line in lines if line]
    items = []
    for line in candidates:
        line = _WHITESPACE_RE.sub(" ", line).replace("**", "").strip()
        if not line:
            continue
        if len(line) > max_chars:
            line = line[:max_chars].rstrip() + "…"
        items.append(line)
    return items[:max_items]


def _strip_leading_rating(text: str) -> str:
    """Drop a leading ``Rating: [[N]]`` so the rationale after it survives."""
    for pattern in (_RATING_RE, _BARE_RATING_RE):
        match = pattern.search(text)
        if match:
            return text[match.end() :].strip()
    return text.strip()


def _load_model(
    model_id: str, device: str, dtype: torch.dtype, device_map: str | None = None
) -> tuple[PreTrainedTokenizerBase, PreTrainedModel]:
    print(f"Loading tokenizer: {model_id}")
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    print(f"Loading model: {model_id} (dtype={dtype}, device={device_map or device})")
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=dtype,
        device_map=device_map or device,
    )
    model.eval()
    return tokenizer, model
