# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

"""ONNX-specific model adaptations to use checkpoints generated by AI Hub Models."""

import subprocess
import sys

from GenAITests.shared.helpers.yaml_config_parser import YAMLConfigParser
from GenAITests.shared.models.generator import HubCompatibleGenerator
from GenAITests.shared.helpers.export import get_test_artifacts_path


@YAMLConfigParser.register_adaptation("AIHM", model_type="*", exclusive=True)
class AIHMAdaptation:
    """Adaptation for loading AIHM-generated checkpoints.

    If qai_hub_models is installed and the model_id is supported,
    this adaptation can generate the model automatically.
    Otherwise, it expects an AIHM checkpoint path.
    """

    # Mapping of HuggingFace model_id to qai_hub_models module path
    SUPPORTED_MODELS: dict[str, str] = {
        "meta-llama/Llama-3.2-1B-Instruct": "qai_hub_models.models.llama_v3_2_1b_instruct",
        "meta-llama/Llama-3.2-3B-Instruct": "qai_hub_models.models.llama_v3_2_3b_instruct",
        "Qwen/Qwen3-4B": "qai_hub_models.models.qwen3_4b",
    }

    @classmethod
    def _is_qai_hub_models_available(cls) -> bool:
        """Check if qai_hub_models package is installed."""
        try:
            import qai_hub_models

            return True
        except ImportError:
            return False

    @classmethod
    def instantiate_model(cls, model_id: str, *args, **kwargs) -> str:
        """Generate an AIHM checkpoint for the given model.

        Args:
            model_id: HuggingFace model ID

        Returns:
            Path to the generated checkpoint
        """
        if not cls._is_qai_hub_models_available():
            raise RuntimeError(
                "qai_hub_models package is not installed. "
                "Please install it or provide a pre-generated AIHM checkpoint path."
            )

        if model_id not in cls.SUPPORTED_MODELS:
            supported = list(cls.SUPPORTED_MODELS.keys())
            raise RuntimeError(
                f"Model '{model_id}' is not supported by AIHM adaptation. "
                f"Supported models: {supported}. "
                f"Alternatively, provide a pre-generated AIHM checkpoint path."
            )

        module_path = cls.SUPPORTED_MODELS[model_id]
        output_path = get_test_artifacts_path(None)

        # Call the model's quantize script to generate a checkpoint. Note that the encodings in the checkpoint
        # are ignored, so we pass in a single quantization sample to minimize checkpoint production time
        cmd = [
            sys.executable,
            "-m",
            f"{module_path}.quantize",
            "-o",
            output_path,
            "--num-samples",
            "1",
        ]

        print(
            f"Generating AIHM checkpoint for model '{model_id}' using command: {' '.join(cmd)}. "
            f"WARNING: This process can take several minutes depending on the model size and system performance."
        )
        try:
            subprocess.run(
                cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE
            )
            print(f"AIHM checkpoint generated at: {output_path}")
        except subprocess.CalledProcessError as e:
            error_msg = e.stderr.decode() if e.stderr else "Unknown error"
            raise RuntimeError(
                f"Failed to generate AIHM checkpoint for model '{model_id}'. "
                f"Command: {' '.join(cmd)}. Error: {error_msg}"
            ) from e

        return output_path

    @staticmethod
    def get_generator_cls():
        return HubCompatibleGenerator
