name: CI pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches: [ develop ]

jobs:
  pipeline:
    if: github.server_url != 'https://github.com'
    uses: ./.github/workflows/pipeline.yml
    secrets: inherit
