name: Fast Release Nightly CI/CD Pipeline

on:
  schedule:
    # 11 PM PDT -- (since GitHub Actions run in UTC)
    - cron: '0 6 * * *'

  # Run the workflow manually from the Actions tab
  workflow_dispatch:

  # Call workflow from other workflows
  workflow_call:
    inputs:
      ref_name:
        description: "Branch to run nightly tests on"
        required: true
        type: string

jobs:
  pre-commit-check:
    name: "Pre-commit check"
    if: github.repository_owner != 'qualcomm'
    uses: ./.github/workflows/pre-commit.yml

  set_vars:
    name: Set pipeline variables
    runs-on: ubuntu-latest
    needs: pre-commit-check
    outputs:
      ref_name: ${{ steps.set_branch_name.outputs.REF_BRANCH }}
    steps:
      - name: Set input ref_name if provided, otherwise current working ref
        id: set_branch_name
        run: |
          if [[ -n "${{ inputs.ref_name }}" ]]; then
            REF_BRANCH="${{ inputs.ref_name }}"
          else
            REF_BRANCH="${{ github.ref_name }}"
          fi

          echo "REF_BRANCH=${REF_BRANCH}" >> "$GITHUB_OUTPUT"
          echo "Using ref_name: ${REF_BRANCH} for nightly."

  variants:
    # TODO: #6790 enable testing with python 3.11 and 3.13
    name: Define supported AIMET variants
    runs-on: ubuntu-latest
    needs: set_vars
    outputs:
      matrix: ${{ steps.final.outputs.value }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.set_vars.outputs.ref_name }}
      - name: Torch variants
        run: |
          VALUE=$(echo "${VALUE:-"{}"}" | jq -c '.include += [
              {
                 "id":              "torch-cpu",
                 "VER_PYTHON_BUILD": "3.12",
                 "VER_PYTHON_TEST":  "3.12,3.10",
                 "VER_TORCH":       "2.*",
                 "VER_ONNXRUNTIME": "",
                 "VER_CUDA":        "",
                 "RUN_UNIT_TESTS":    "ON",
                 "RUN_ACCEPTANCE_TESTS":    "ON",
                 "BUILD_TARGETS":   "all",
                 "PIP_INDEX":       ""
              },
              {
                 "id":              "torch-gpu",
                 "VER_PYTHON_BUILD": "3.12",
                 "VER_PYTHON_TEST":  "3.12",
                 "VER_TORCH":       "2.*",
                 "VER_ONNXRUNTIME": "",
                 "VER_CUDA":        "12.6.3",
                 "RUN_UNIT_TESTS":    "ON",
                 "RUN_ACCEPTANCE_TESTS":    "ON",
                 "BUILD_TARGETS":   "all",
                 "PIP_INDEX":       ""
              }
            ]')
          echo "VALUE=$VALUE" >> $GITHUB_ENV
      - name: ONNX variants
        run: |
          VALUE=$(echo "${VALUE:-"{}"}" | jq -c '.include += [
              {
                 "id":              "onnx-cpu",
                 "VER_PYTHON_BUILD": "3.12",
                 "VER_PYTHON_TEST":  "3.12,3.10",
                 "VER_TORCH":       "",
                 "VER_ONNXRUNTIME": "1.19.2",
                 "VER_CUDA":        "",
                 "RUN_UNIT_TESTS":    "ON",
                 "RUN_ACCEPTANCE_TESTS":    "ON",
                 "BUILD_TARGETS":   "all",
                 "PIP_INDEX":       ""
              },
              {
                 "id":              "onnx-gpu",
                 "VER_PYTHON_BUILD": "3.12",
                 "VER_PYTHON_TEST":  "3.12",
                 "VER_TORCH":       "",
                 "VER_ONNXRUNTIME": "1.19.2",
                 "VER_CUDA":        "12.6.3",
                 "RUN_UNIT_TESTS":    "ON",
                 "RUN_ACCEPTANCE_TESTS":    "ON",
                 "BUILD_TARGETS":   "all",
                 "PIP_INDEX":       ""
              }
            ]')
          echo "VALUE=$VALUE" >> $GITHUB_ENV

      - name: Doc variants
        run: |
          VALUE=$(echo "${VALUE:-"{}"}" | jq -c '.include += [
              {
                 "id":              "onnx-torch-cpu",
                 "VER_PYTHON_BUILD": "3.12",
                 "VER_PYTHON_TEST":  "3.12",
                 "VER_TORCH":       "2.*",
                 "VER_ONNXRUNTIME": "1.19.2",
                 "VER_CUDA":        "",
                 "RUN_UNIT_TESTS":    "OFF",
                 "RUN_ACCEPTANCE_TESTS":    "OFF",
                 "BUILD_TARGETS":   "all;doc",
                 "PIP_INDEX":       ""
              }
            ]')
          echo "VALUE=$VALUE" >> $GITHUB_ENV

      - name: (Last step) Generate few extra properties for each variant
        id: final
        run: |
          echo "value=$VALUE" >> $GITHUB_OUTPUT

  call-build-wheels:
    name: Call build-wheels
    needs: [ variants ]
    uses: ./.github/workflows/build-wheels.yml
    with:
      variants: ${{ needs.variants.outputs.matrix }}
      build-windows-wheel: true
    secrets: inherit

  call-unit-acceptance-tests:
    name: Run unit and acceptance tests
    needs: [ variants, call-build-wheels ]
    uses: ./.github/workflows/run-unit-acceptance-tests.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.variants.outputs.matrix) }}
    with:
      ver_python: ${{ matrix.VER_PYTHON_TEST }}
      ver_cuda: ${{ matrix.VER_CUDA }}
      ver_torch: ${{ matrix.VER_TORCH }}
      ver_onnxruntime: ${{ matrix.VER_ONNXRUNTIME }}
      env_name: ${{ matrix.id }}
      run_unit_tests: ${{ matrix.RUN_UNIT_TESTS == 'ON' }}
      run_acceptance_tests: ${{ matrix.RUN_ACCEPTANCE_TESTS == 'ON' }}
      pip_index: ${{ matrix.PIP_INDEX }}
      include_windows_tests: true
    secrets: inherit

  notify_failure:
    if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) && github.event_name == 'schedule' && github.run_attempt == '1' }}
    name: Notify failure on slack
    needs: [ call-build-wheels, call-unit-acceptance-tests ]
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.25.0
      with:
        channel-id: C0898PQVA31
        slack-message: "AIMET Nightly Failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFIER_TOKEN }}
