name: "Changed files"

description: "Get list of changed file"

inputs:
  files:
    description: "File(s) to compare"
    required: false
    default: ""
  base_sha:
    description: "Base commit id to compare the diff with"
    required: false
    default: ""

outputs:
  changed_files:
    description: "List of changed files"
    value: ${{ steps.diff.outputs.value }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Get list of changed files
      id: diff
      shell: bash
      run: |
        set -x
        if [[ "${{ inputs.base_sha }}" != "" ]] ; then
          BASE_SHA="${{ inputs.base_sha }}"
        else
          git config extensions.partialClone true
          git fetch --no-tags --unshallow --filter=tree:0
          BASE_SHA=$(git merge-base origin/${{ github.event.repository.default_branch }} HEAD)
        fi

        echo "value=$(git diff --name-only ${BASE_SHA}..HEAD -- ${{ inputs.files }} | tr '\n' ' ')" >> $GITHUB_OUTPUT
